### ISSUE TITLE
Test Doppler shift correction and integrate it at the FM demodulation flowgraph

### ISSUE THREAD

**Issue by surligas** [satnogs/gr-satnogs#18]

**Comment by surligas** [comment]
Check frequency stability issue.

**Comment by cshields** [comment]
Given the success we have had this week decoding demodulated data with doppler shift correction, I'd say this is fixed.

**Comment by surligas** [comment]
Ok @cshields thanks a lot. I close this and I will open a new one to test the other more fine grained doppler correction block.
