### ISSUE TITLE
Change the required GNU Radio version

### ISSUE THREAD

**Issue by surligas** [satnogs/gr-satnogs#19]

**Comment by cshields** [comment]
Where/what was the change?  IIRC the required version in dev exceeded the version we can get out of the box for jessie on rpi.  Did we downgrade the required version somewhere?

**Comment by surligas** [comment]
We discussed a little about this in a meeting. Every attempt to support jessie was a dead-end. The only solution was to compile the gnuradio from source, but for many this would be a great problem. So eventually we ended up choosing a more upstream distro. Fedora works like a charm.

**Comment by cshields** [comment]
great, I'll give it a shot!
