### ISSUE TITLE
Extract the waterfall of an observation

### ISSUE THREAD

**Issue by surligas** [satnogs/gr-satnogs#42]

**Comment by cshields** [comment]
@surligas do you have any samples or dimensions we can use in satnogs/satnogs-network#276 ?

**Comment by surligas** [comment]
The satnogs_waterfall.pg takes as parameters the height and the width of the image. By default is 800x800. 
![waterfall](https://cloud.githubusercontent.com/assets/1844631/22184492/34f1fb20-e0db-11e6-97ec-17f7c3ee3fcd.png)

**Comment by cshields** [comment]
everything is committed/works
