### ISSUE TITLE
Add an ogg vorbis source block

### ISSUE THREAD

**Issue by kerel-fs** [satnogs/gr-satnogs#62]
Currently we need to convert the ogg vorbis encoded files from network to wav to use them with the wav file source block. This could be done with
```
sox infile.ogg output.wav
```
(thanks, @cshields ).

Could you provide an ogg vorbis file source block as you did with the ogg vorbis file sink block?

**Comment by surligas** [comment]
Yeah sure. Is there any requirement on the output data type (shorts, floats) ?

**Comment by cshields** [comment]
Other file sources default to floats...  So we could go with that?

**Comment by surligas** [comment]
Here it is  165423d

Supports multiple ogg streams, but 1 channel should do the job for our ogg files.
