### ISSUE TITLE
clipping in fm demod

### ISSUE THREAD

**Issue by cshields** [satnogs/gr-satnogs#74]
Our FM demodulation process clips a bit.  This is likely to not cause any kind of issue with data as they are short bursts but it is definitely obvious during voice captures.

Listening to the voice capture on SO-50 makes this obvious:  https://network.satnogs.org/observations/3041/

I'm guessing this has something to do with the frequency change and correction?

**Comment by surligas** [comment]
We could possibly place an AGC block after the quadrature demod in order to avoid this voice clipping. Another solution would be to limit the output of the quadrature demod block in the `[-1, 1]` range. This block outputs the result of `atan2()` which is limited in the `[-pi, pi]` range, multiplied by the `gain`  parameter. A proper gain should do the job. 

However, I do not know what is affected exactly. It supposed that the gain is a parameter of the frequency deviation. Perhaps, in our case that we do not perform any filtering at all should not be a problem.

**Comment by cshields** [comment]
I don't think this is going to help at all, and "clipping" was probably a bad way to describe this as it is not an audio clipping issue, but rather what sounds to be a dropped moment in time as we correct for doppler.

Overnight I changed both my FM and CW scripts to use the 'doppler correction' block instead of the 'coarse doppler correction' block to see if that would change things. Did not help: https://network.satnogs.org/observations/3171/

As for AGC, here is a strong CW capture. We do have an AGC2 block on this:  https://network.satnogs.org/observations/3160/

**Comment by csete** [comment]
For trained CW ops it's clearly audible that samples are missing. Very little of it is decodable by ear. You can confirm it by loading the waveform into Audacity then zoom in to see the dots and dashes:

![screenshot_634](https://cloud.githubusercontent.com/assets/306178/25313870/6982226c-2838-11e7-9b6d-44991e736a23.png)

The dots should have equal length (unit length) and the dashes should be 3x unit length. The space between a dash/dot is one unit length and the space between two characters is 3x unit length.

The waveform shows more or less random spacings and lengths, so a lot of samples must be missing.

I would recommend trying to confirm that this is not a CPU load or USB transfer issue. Note that even if the overall CPU load is below max, a single core could be saturated to 100%. Tools like htop can show load on individual cores.

**Comment by cshields** [comment]
> I would recommend trying to confirm that this is not a CPU load or USB transfer issue. Note that even if the overall CPU load is below max, a single core could be saturated to 100%. Tools like htop can show load on individual cores.

Thanks for the visual!

I am going to see if this reproduces on my desktop+airspy..  If it goes away we can further isolate the problem (cpu/usb). Best I can tell this problem is *not* reproduced by the station in Athens, though with the frequency shift they have the usable portion of the capture is lessened: https://network.satnogs.org/observations/2904/

**Comment by cshields** [comment]
discovered today that this issue does not reproduce on a desktop system..  So the software *works*.. now to figure out why we have the issue on the rpi3 and if we can work around it.

**Comment by cshields** [comment]
This was fixed long ago but lowering the incoming sample rate.  1msps on an rtlsdr+rpi3 is the sweet spot and solves the clipping issue.
