### ISSUE TITLE
Update CW Flowgraph Doppler Correction Rate

### ISSUE THREAD

**Issue by darksidelemm** [satnogs/gr-satnogs#93]
The current CW flowgraph has a 1 second update interval for coarse doppler correction. While there is a command line option to vary this, it is not currently used, and the value is hardcoded here:
https://github.com/satnogs/gr-satnogs/blob/master/apps/flowgraphs/cw_demod.grc#L2931

The 1-second update rate leads to severe 'chirpyness' on 70cm birds. As an example, here is a FO-29 pass with the 1-second update rate:
https://network-dev.satnogs.org/observations/2985/

Lowering the update rate to 100ms gives a significant improvement in readability (noting that these passes have very similar doppler profiles):
https://network-dev.satnogs.org/observations/3065/

I'm not sure what the minimum update rate should or can be, but 100ms seems to work well, and is definitely a better default for 70cm sats than 1 seconds.

I should note that I would *not* recommend this fast an update for FSK/GMSK/BPSK flowgraphs, unless it can be proven that the stepping of frequency doesn't affect the performance of the the various modems in use.

**Comment by surligas** [comment]
I would definitely agree on this. `satnogs-client` updates the frequency every 100ms so in theory the update interval in `gr-satnogs` should be 50ms. I will fix the hard-coded value ASAP and set them to a more reasonable default value.  

Your concerns about the modems are right. I think that the doppler correction block will handle this properly, as it performs a smoothed correction between the frequency updates by applying curve fitting. It is time to give it a try.

**Comment by surligas** [comment]
Fixed https://github.com/satnogs/gr-satnogs/pull/94
